### ISSUE TITLE
mismatch of version

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos-docker#2]
Seems there is a problem with GIT workflow in this repository.

The Dockerfiles in `master` refer to `0.23.0-1.0.ubuntu1404` version of mesos. However there is `0.25.0-0.2.70.ubuntu1404` tag and its files refer to `0.25.0-0.2.70.ubuntu1404` version of mesos.

What is the head branch?

**Comment by frankscholten** [comment]
Working on a refactoring right now where all versions are separate folders.

**Comment by frankscholten** [comment]
Refactoring has been merged into master via https://github.com/ContainerSolutions/minimesos-docker/pull/4
